
---
- name: Installer et configurer Nginx
  hosts: webservers
  become: yes
  tasks:

    - name: Mettre à jour les paquets du système
      apt:
        update_cache: yes

    - name: Installer Nginx
      apt:
        name: nginx
        state: present

    - name: Démarrer et activer le service Nginx
      systemd:
        name: nginx
        state: started
        enabled: yes


    - name: Vérifier que Nginx est en cours d'exécution
      command: systemctl status nginx
      register: nginx_status
      changed_when: false

    - name: Afficher le statut de Nginx
      debug:
        msg: "{{ nginx_status.stdout_lines }}"
